### ISSUE TITLE
Wrong library name in #include

### ISSUE THREAD

**Issue by mgrusin** [mpflaga/Arduino_Library-vs1053_for_SdFat#2]
FYI, the "fileplayer" and "webplayer" examples won't compile because they #include <vs1053.h> when they should #include <vs1053_SdFat.h>.

Thanks as always!

**Comment by mpflaga** [comment]
thanks, I have correct the typo's and validated that they compile and reissued a new release, that I would expect the Arduino Package manger will pickup within 24 hours.

**Comment by menway** [comment]
I just imported this library (latest version: 1.3.0) from Arduino IDE menu and the header file name is still incorrect in example files ```fileplayer.ino``` and ```webplayer.ino```.

```
#include <vs1053.h>
```

Also the library link goes to a github 404 page (https://github.com/mpflaga/vs1053_sdfat). 

Seems the newer released version 1.3.1 was not indexed by Arduino IDE?
