### ISSUE TITLE
Add support for audio recording?

### ISSUE THREAD

**Issue by menway** [mpflaga/Arduino_Library-vs1053_for_SdFat#9]
Hi mpflaga, thank you for the library. It saved me a whole day!

I have got this shield https://www.geeetech.com/wiki/index.php/Arduino_MP3_shield_board_with_TF_card and it claims to support for "OGG encoding real-time recording". But I couldn't find recording related codes in this library and when I took a look at https://mpflaga.github.io/Arduino_Library-vs1053_for_SdFat/ and it said "As most commercially available shields do not support audio input this feature has not been implemented"

Now it's 2020 and maybe some newer shields have added the recording ability physically so could you please consider adding support for the audio recording feature?

Thank you very much.

**Comment by mpflaga** [comment]
I never got to a point to record audio with this project. 
I have seen that Adafruit re-factored this library into a much simpler version. And it looks to claim supporting the recording.
https://learn.adafruit.com/adafruit-vs1053-mp3-aac-ogg-midi-wav-play-and-record-codec-tutorial/ogg-recorder
